from setuptools import setup, find_packages

setup(
    name="screw_data_loading",
    version="0.1.0",
    author="Nikolai West",
    author_email="nikolai.west@tu-dortmund.de",
    description="A tool to load and preprocess screw data from multiple JSON files",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/nikolaiwest/scre_data_loading",
    packages=find_packages(),
    install_requires=[
        "numpy",
        "tqdm",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "Topic :: Scientific/Engineering :: Data Science",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Utilities",
    ],
    python_requires=">=3.6",
)
