CREATE TABLE IF NOT EXISTS screw_steps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    screw_run_id TEXT,
    step_number, INT,
    raw_json TEXT,
    step_type TEXT,
    row TEXT,
    column TEXT,
    name TEXT,
    last_cmd TEXT,
    quality_code TEXT,
    speed INTEGER,
    category INTEGER,
    docu_buffer INTEGER,
    result TEXT,
    angle_threshold_nom REAL,
    angle_threshold_act REAL,
    tf_torque_nom REAL,
    tf_torque_act REAL,
    tightening_functions TEXT,
    torsion_release INTEGER,
    angle_values TEXT,
    torque_values TEXT,
    gradient_values TEXT,
    torquered_values TEXT,
    anglered_values TEXT,
    time_values TEXT,
    FOREIGN KEY (screw_run_id) REFERENCES screw_runs (id)
);
